// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWindowPosition() {
  return window['go']['main']['App']['GetWindowPosition']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadConfig(arg1) {
  return window['go']['main']['App']['LoadConfig'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function Print(arg1) {
  return window['go']['main']['App']['Print'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectApk() {
  return window['go']['main']['App']['SelectApk']();
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function StartPack(arg1) {
  return window['go']['main']['App']['StartPack'](arg1);
}
