// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function GetWindowPosition():Promise<Record<string, number>>;

export function Greet(arg1:string):Promise<string>;

export function LoadConfig(arg1:string):Promise<main.Config>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function Print(arg1:string):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SelectApk():Promise<string>;

export function Start(arg1:string):Promise<void>;

export function StartPack(arg1:models.PreParams):Promise<void>;
